name: API CI

on: [push]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Run Black
        run: black api/ --check --diff

      - name: Run Flake8
        run: flake8 api/ --max-line-length=88

      - name: Run Pytest
        run: PYTHONPATH=. pytest api/tests
